name: Python Tests

on:
  push:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          . venv/bin/activate  # Для Linux/macOS

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest  # Если pytest не в requirements.txt

      - name: Run tests
        run: |
          pytest -v  # -v для подробного вывода